name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: docs/main.typ
      - name: Upload PDF Result
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: *.pdf
